server:
  port: 8083

spring:
  application:
    name: auth-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix-stack

security:
  oauth2:
    authorization:
      jwt:
        keyStore: classpath:jwt.jks
        keyStorePassword: mypass
        keyAlias: jwt
        keyPassword: mypass
    client:
      clientId: apiGatewayClient
      clientSecret: apiGatewaySecret
      authorizedGrantTypes:
        - password
        - refresh_token
      scope:
        - all

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
