spring:
  application:
    name: api-gateway

server:
  port: 8885

# read https://github.com/netstalk3r/globalrep/tree/master/oauth2-password-behind-zuul

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmq8h2/BNI2upz/4cChSO
          /TDy/929Xo/MnhFIn9YlecLNZ6x26JxhPxYmN6/AdIdlNWoP7hd1YSYgnT+0Sy2i
          UWEU9KNAbR0k2RMKRd35OgLR/+7LHNrLBZAjYgGaiDiVDCgIH+g5mmYjz51+r2Ma
          o6zm4Ibp4Vjv++Udb+ua/kOtoAk2ImtqfvtI408gJDQNd2GaDSUSMSvxlCmLidE/
          IxZt5WSw0ixszGIhgNLhf13vgnsFszfh0AiJpvRi5aiTtJ0wOiCLEVWLK3Ed64Ap
          KgGHQaer62M+yZjWboxbMypanmUu8x60brULKLXCk4U5TJUVWklJDHcmrpLoywC+
          3QIDAQAB
          -----END PUBLIC KEY-----
    # sso:
    #   loginPath: /login
    client:
      # accessTokenUri: http://localhost:8894/oauth/token // TODO przeniesc to do filtra zuulowego?
      clientId: apiGatewayClient
      clientSecret: apiGatewaySecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8884/eureka/

zuul:
  prefix: /api/v1
  routes:
    login:
      sensitiveHeaders:
      path: /login
      serviceId: auth-server

    refresh-token:
      sensitiveHeaders:
      path: /refresh-token
      serviceId: auth-server

    # auth-service:
    #   sensitiveHeaders:
    #   path: /auth/**
    #   serviceId: auth-server

    user-service:
      sensitiveHeaders:
      path: /users/**
      serviceId: user-service

    note-service:
      sensitiveHeaders:
      path: /notes/**
      serviceId: note-service