spring:
  application:
    name: api-gateway

server:
  port: 8885

# read https://github.com/netstalk3r/globalrep/tree/master/oauth2-password-behind-zuul

security:
  oauth2:
    resource:
      jwt:
        keyValue: 123
    # sso:
    #   loginPath: /login
    client:
      # accessTokenUri: http://localhost:8894/oauth/token
      clientId: apiGatewayClient
      clientSecret: apiGatewaySecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8884/eureka/

zuul:
  prefix: /api/v1
  routes:
    login:
      sensitiveHeaders:
      path: /login
      serviceId: auth-server

    refresh-token:
      sensitiveHeaders:
      path: /refresh-token
      serviceId: auth-server

    # auth-service:
    #   sensitiveHeaders:
    #   path: /auth/**
    #   serviceId: auth-server

    user-service:
      sensitiveHeaders:
      path: /users/**
      serviceId: user-service

    note-service:
      sensitiveHeaders:
      path: /notes/**
      serviceId: note-service