spring:
  application:
    name: api-gateway

server:
  port: 8885

# read https://github.com/netstalk3r/globalrep/tree/master/oauth2-password-behind-zuul

security:
  oauth2:
    client:
      # accessTokenUri: http://auth-server/auth/oauth/token
      clientId: client
      clientSecret: secret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8884/eureka/

zuul:
  prefix: /api/v1
  routes:
    auth-service:
      sensitiveHeaders:
      path: /auth/**
      serviceId: auth-server

    note-service:
      path: /notes/**
      serviceId: note-service