spring:
  application:
    name: api-gateway

server:
  port: 8885

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8884/eureka/

zuul:
  prefix: /api/v1
  routes:
    auth-service:
      sensitiveHeaders:
      path: /auth/**
      serviceId: auth-server

    note-service:
      path: /notes/**
      serviceId: note-service