server:
  port: 8081

spring:
  application:
    name: api-gateway

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp73kr0NNQ1pzW0Sunx/b
          kmRvJZpzhjIqwbNQoqVo601U949Gv4SoGtJ4YFceH9ttqrFH/TCjQDF+fI0+h7w0
          90JY+iO0+V37PoL3M/3/YimGRFV8rrJrji4ViTmHxH7qxO5J5tIr7SiA1+wDdNB5
          R/2b9WGHOFNRfaEAb5CWlJT3B6yFHs16UuIV4J/AM0me9C9z5KvSuVbrY+D4l4fB
          tHl/VMcjo3TCu517b04/kSKbpe6xQMp/9gGBhZtalhVDl2xGw2p2mILRmrsKABaz
          a+tFCcdHu7ak7irJyAga59cqMwYJkxkdXJSmG3ddajQqz8bQ9hxyMeeMxivKA/sw
          LQIDAQAB
          -----END PUBLIC KEY-----
    client:
      clientId: apiGatewayClient
      clientSecret: apiGatewaySecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

zuul:
  prefix: /api/v1
  routes:
    login:
      sensitiveHeaders:
      path: /login
      serviceId: auth-server

    refresh-token:
      sensitiveHeaders:
      path: /refresh-token
      serviceId: auth-server

    user-service:
      sensitiveHeaders:
      path: /users/**
      serviceId: user-service
      stripPrefix: false

    file-service:
      sensitiveHeaders:
      path: /files/**
      serviceId: file-service
      stripPrefix: false

file-service:
  ribbon:
    ReadTimeout: 60000 # increase read timeout for file upload
