spring:
  application:
    name: image-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix-stack # TODO change to 27018
  servlet:
    multipart:
      enabled: false # disable multipart to efficiently handle large files # TODO

server:
  port: 8085

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmq8h2/BNI2upz/4cChSO
          /TDy/929Xo/MnhFIn9YlecLNZ6x26JxhPxYmN6/AdIdlNWoP7hd1YSYgnT+0Sy2i
          UWEU9KNAbR0k2RMKRd35OgLR/+7LHNrLBZAjYgGaiDiVDCgIH+g5mmYjz51+r2Ma
          o6zm4Ibp4Vjv++Udb+ua/kOtoAk2ImtqfvtI408gJDQNd2GaDSUSMSvxlCmLidE/
          IxZt5WSw0ixszGIhgNLhf13vgnsFszfh0AiJpvRi5aiTtJ0wOiCLEVWLK3Ed64Ap
          KgGHQaer62M+yZjWboxbMypanmUu8x60brULKLXCk4U5TJUVWklJDHcmrpLoywC+
          3QIDAQAB
          -----END PUBLIC KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
