spring:
  application:
    name: note-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix-stack

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
